"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_mocha"

format = """$username $directory$all\
$character"""

right_format = """$cmd_duration"""

[directory]
truncation_length = 4
truncation_symbol = "…/"
style = "bold lavender"
repo_root_style = "bold peach"
format = '[$path]($style)[$read_only]($read_only_style) '

# Making a single line prompt
[line_break]
disabled = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[time]
disabled = true
format = ' [\[ $time \]]($style) '
time_format = "%T"
time_range = "00:00:00-24:00:00"
use_12hr = false
style = "bold green"

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[username]
style_user = "surface2"
style_root = "mauve"
format = "[$user]($style)"
disabled = false
show_always = true
aliases = { "Cory.Dahlstrand" = "Cory", "Administrator" = "Admin" }

[git_status]
style = "flamingo"
up_to_date = "[✓](green)"
stashed = "[󰴮$count](surface2)"
disabled = false
modified = '[$count](yellow)'
staged = '[+$count](green)'
deleted = '[$count](red)'
ahead = '[$count](sapphire)'
behind = '[$count](mauve)'
diverged = "[$ahead_count](sapphire)[$behind_count](mauve)"

[git_branch]
symbol = ""
style = "flamingo"
format = '[$symbol $branch]($style) '

[python]
disabled=true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"